### ISSUE TITLE
Add scraper for GitHub issues

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-tooling/github-updates#2]
The tool currently scrapes repositories, PRs open in those repositories, releases in those repositories in last x configured days. The current request is to scrape GitHub issues for each of those repositories.
1. Scrape issues
2. Filter issues based on the input tag

**Comment by arnabkaycee** [comment]
Can we mark this as closed w.r.t. PR #8 ?

**Comment by arsulegai** [comment]
Yes, this has been implemented.
