### ISSUE TITLE
Create Jekyll theme website

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-tooling/github-updates#4]
Jekyll theme website should read `.md` files which has list of PRs, issues, releases etc information captured there.
Use `https://github.com/arsulegai/start-here-hyperledger` for website/`.md` files.

**Comment by arnabkaycee** [comment]
How would the markdown files look like? Any suggestions on the table structure for issues?
Also, once the `md` files are generated, do we overwrite the old `md` or keep the old files?

**Comment by arsulegai** [comment]
1. To start with - we could keep the old `.md` files as well or update the same with new list of issues.
2. I do not have suggestion on the jekyll theme or the structure of `.md` file. We can search for free templates and then model our output to meet the template requirement. Feel free to suggest a template.

**Comment by arnabkaycee** [comment]
Few suggestions for a Jekyll theme:

- [Simple and minimalistic](http://jekyllthemes.org/themes/persephone/)
- [Minimal with some colors](http://jekyllthemes.org/themes/jekyll-pug-material/)
- [Modern blog with nice placeholders](https://alembic.darn.es/)
- [Another minimalistic](https://www.amitmerchant.com/reverie/introducing-reverie-jekyll-theme/)

**Comment by arsulegai** [comment]
I like https://www.amitmerchant.com/reverie/introducing-reverie-jekyll-theme/ that looks elegant and has an example where pagination can be seen. Let's say we add a page for each project or per language. This should be good for us to use.

**Comment by arnabkaycee** [comment]
> I like https://www.amitmerchant.com/reverie/introducing-reverie-jekyll-theme/ that looks elegant and has an example where pagination can be seen. Let's say we add a page for each project or per language. This should be good for us to use.

But how would the pages for each project from labs or hyperledger look like? Wouldn't it get a bit cluttered if we put all projects as the top nav panel?

**Comment by arsulegai** [comment]
The repository https://github.com/arsulegai/start-here-hyperledger is setup
