### ISSUE TITLE
Add a filter or configuration through ENV to specify what to run

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-tooling/github-updates#9]
The tool initially started to run and get pending PRs. However, as time progressed it increased its scope. Each request made to GitHub through API is counted as an attempt to DDoS. GitHub API server would block the request if the frequency is too high.

It will help if the configuration is restructured such that one can specify which of the given options to be run. Ex: get me PRs alone, get me issues alone, get me releases alone etc.

**Comment by arnabkaycee** [comment]
I can pick up this issue. Shall we pass the options through command line arguments or in the `config.yaml`?

**Comment by arsulegai** [comment]
It will help if it is passed in `config.yaml` file. This can be done along with cleanup of that file. i.e. Let each section have a `enabled` kind of flag along with its own configuration in terms of time for which the details are to be scraped.

**Comment by arsulegai** [comment]
Thanks @arnabkaycee for enabling this
